### ISSUE TITLE
Feat: getting basic metrics in ipfs-companion

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-companion#1115]
**Is your feature request related to a problem? Please describe.**
We will be adding basic metrics to ipfs-companion, and this issue is the parent tracking issue for getting those metrics into ipfs-companion

**Describe the solution you'd like**
Be able to track the following basic metrics:

1. Daily active users
2. Weekly active users
3. monthly active users
4. How many times is the ipfs-companion extension icon is clicked (extension modal is viewed)
5. How many times the settings page is viewed

see https://github.com/ipfs/ipfs-gui/issues/125 for more information

**Describe alternatives you've considered**

see https://github.com/ipfs/ipfs-gui/issues/125 for more information

**Additional context**

#### Children tasks

- [x] https://github.com/ipfs/ipfs-companion/issues/1114
- [x] Update https://github.com/ipfs/ipfs-companion/blob/main/PRIVACY-POLICY.md
    - [x] "Last Update:" date
    - [ ] "What Information Do We Collect?" section to explain clearly what data we collect now and point to ipfs/ipfs-gui#125

Parent: https://github.com/ipfs/ipfs-gui/issues/105
Metrics discussion issue: https://github.com/ipfs/ipfs-gui/issues/125

**Comment by lidel** [comment]
A hard requirement is the ability to opt-out and  disable sending ALL metrics via Preferences screen – see rationale in  https://github.com/ipfs/ipfs-gui/issues/125#issuecomment-1352295236

**Comment by SgtPooki** [comment]
currently have the following: 
![image](https://user-images.githubusercontent.com/1173416/208003469-108391d0-4ecb-46e0-b9b5-565ddb630e09.png)

Would love any initial feedback you have on this and https://github.com/ipfs/ipfs-companion/issues/1114 prior to you leaving for the holidays =)

**Comment by lidel** [comment]
@SgtPooki interface looks good. Having that in Companion Preferences makes it easy to discover, if anyone cares.
