### ISSUE TITLE
Create WebExtensions Experiments to Prototype Missing APIs

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#343]
## Background

> WebExtensions are a cross-browser system for developing browser add-ons.

Chrome is quite conservative and rarely adds a new API. 
Firefox is different, there is a transparent process for [triaging](https://wiki.mozilla.org/WebExtensions/Triage) requests for new APIs, plus there is a special SDK for creating [ WebExtensions Experiments ](https://webextensions-experiments.readthedocs.io/en/latest/). 

> WebExtensions Experiments allow developers to write experimental WebExtensions APIs for Firefox. 
> **They can be used to prototype APIs for landing in Firefox, or for use on Nightly or Developer Edition.**

**tl;dr** the chance of new API being added to Firefox is much higher if a prototype implementation is provided.

## Missing APIs

List extracted from [Roadblocks for "native" IPFS in Browser Extension](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md):

- [ ] **[Problem #1: Inability to Inject HTTP Responses by WebExtension](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md#problem-1-inability-to-inject-http-responses-by-webextension)**
- [ ] [Problem #2: Inability to Control How Origin Is Calculated](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md#problem-2-inability-to-control-how-origin-is-calculated)
- [ ] [Problem #3: Inability to Control Address in Location Bar](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md#problem-3-inability-to-control-address-in-location-bar) 

## References

- https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md
- https://webextensions-experiments.readthedocs.io/en/latest/
- https://github.com/web-ext-experiments

**Comment by cvan** [comment]
Is there a Firefox Bugzilla platform bug filed for [Problem #1](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md#problem-1-inability-to-inject-http-responses-by-webextension)?

**Comment by lidel** [comment]
AFAIK all three problems come from my thoughts around this bug: 
-  [Bug 1271553 - Add ability to implement programmable custom protocol handler](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553), namely:
     - "Problems 2&3" were born in [comment 47](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553#c47)
       (note that it is 1 year old, was written before our `browser.protocol` PoC in Brave)
    - "Problem 1" – [comment 52](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553#c52)
